swiftmailer:
    url: '%env(MAILER_URL)%'
#    transport:        gmail
#    username:         me.media.dev@gmail.com
#    password:         '%env(GMAIL_PASSWORD)%'
#    host:             localhost
#    port:             465
#    encryption:       ssl
#    auth-mode:        login
#    spool: { type: 'memory' }
#    stream_options:
#        ssl:
#            allow_self_signed: true
#            verify_peer: false
#            verify_peer_name: false
